Gr01.6
ssc-spc-ccoe-cei/aws-guardrails-cac-solution pull request #84
Opened 2024-12-10 18:17 UTC by TylerTMizuyabu

# AWS CAC Solution PR Template

## Pull Request Type
- [x] New Feature
- [ ] Bugfix
- [ ] Documentation Update
- [ ] Other (Please specify)

## Description

Adds a lambda for guardrail check 1.06. This lambda queries Identity Center and IAM for all users, then checks their policies. It gives compliant if there is at least one privilegeduser with admin access, and if no non-privileged users have admin access.

Also updates 02 because I believe the backslash isn't needed to escape the '{' character

## Related Issue(s)
List any related issues here. Include `Fixes #issue_number` or `Closes #issue_number` if applicable.

## How Has This Been Tested?
Describe how you have tested these changes. Include details of the testing environment and the tests you ran to verify the functionality.

### CloudFormation Linter Results
Include the output of the CloudFormation linter (if used).

### Deployment Test Results
Provide details of any deployment tests you have conducted.

## Screenshots (if appropriate)

## Checklist:
- [ ] My code follows the code style of this project.
- [ ] I have updated any related documentation.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.
- [ ] My changes generate no new warnings.
- [ ] I have added comments to my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes require a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have checked that the final deliverable aligns with the CloudFormation best practices.

## Additional Notes
Include any additional information that you think is important for reviewers.

2024-12-10 20:19 UTC, david-dearden-ssc requested changes

2024-12-10 20:19 UTC, david-dearden-ssc commented on src/lambda/gc01_check_dedicated_admin_account/app.py
> +        admin_permssion_sets_by_account=get_admin_permission_sets_for_instance_by_account(instance_arn)
```suggestion
        admin_perimssion_sets_by_account=get_admin_permission_sets_for_instance_by_account(instance_arn)
```

2024-12-10 20:21 UTC, TylerTMizuyabu commented on src/lambda/gc01_check_dedicated_admin_account/app.py
> +        users_by_instance[instance_id]
I think this line was leftover from some debuging. doesn't blow up. I have the function running on lza

2024-12-10 20:24 UTC, TylerTMizuyabu commented on src/lambda/gc01_check_dedicated_admin_account/app.py
> +        return policies
Inline policies we need to actually look at their policy doc statements so we have to fetch that information. The managed one we don't and also I don't think we can. At least I haven't been able to find an AWS api that does this for managed policies

2024-12-10 20:25 UTC, david-dearden-ssc commented on src/lambda/gc01_check_dedicated_admin_account/app.py
> +        return policies
Ah, ok, makes sense, I guess `policies_grant_admin_access` has a fallback for a missing policy document.

2024-12-10 20:28 UTC, TylerTMizuyabu commented on src/lambda/gc01_check_dedicated_admin_account/app.py
> +        users_by_instance[instance_id]
actually I meant to initialize the list here so the next comment wouldn't be an issue

2024-12-10 20:37 UTC, TylerTMizuyabu commented on src/lambda/gc01_check_dedicated_admin_account/app.py
> +                users_by_instance[instance_arn] = users_by_instance[instance_arn] + response.get("Users", [])
response to previous comment fixes this

2024-12-10 20:37 UTC, david-dearden-ssc requested changes

2024-12-10 20:37 UTC, david-dearden-ssc commented on src/lambda/gc01_check_dedicated_admin_account/app.py
> +        users_by_instance[instance_id] = []
```suggestion
        users_by_instance[instance_arn] = []
```

2024-12-10 20:40 UTC, TylerTMizuyabu commented on src/lambda/gc01_check_dedicated_admin_account/app.py
> +        return policies
yeah it takes in managed and inline policies as different parameters right. So it treats them differently. for managed policies we are just looking at the name and no policy doc. We actually don't expect the objects in that list to have a policy doc. For inline policies we expect the policy doc to be there

2024-12-10 20:41 UTC, TylerTMizuyabu commented on src/lambda/gc01_check_dedicated_admin_account/app.py
> +        response = AWS_SSO_ADMIN_CLIENT.list_account_assignments(AccountId=account_id, InstanceArn=instance_arn, PermissionSetArn=permission_set_arn)
yup, updated to loop

2024-12-10 21:32 UTC, david-dearden-ssc approved these changes

2024-12-11 21:54 UTC, a-shokri-ssc approved these changes

2024-12-11 22:47 UTC, merged